version: '2.4'
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
        restart: always
        volumes:
            - ./init.sql:/data/application/init.sql
        environment:
            - MYSQL_ROOT_PASSWORD=diaryJournal
        networks:
            - journal-network
    node:
        build:
            context: .
            dockerfile: Dockerfile
        ports: [3000:3000]
        environment:
            - PORT=3000
            - HOST=localhost:3000
            - JOURNAL_DB_NAME=Journal
            - JOURNAL_DB_HOST=db
            - JOURNAL_DB_USER=root
            - JOURNAL_DB_PASS=diaryJournal
        volumes:
            - ./:/usr/src/app/
        networks:
            - journal-network
        depends_on: [db]
        restart: always
networks:
    journal-network:
        driver: bridge
