version: '2.4'
services:
    auth_db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
        cap_add:
            - SYS_NICE 
        restart: always
        volumes:
            - ./init.sql:/data/application/init.sql
        environment:
            - MYSQL_ROOT_PASSWORD=diaryJournal
        networks:
            - journal-network
    auth_node:
        build:
            context: .
            dockerfile: Dockerfile
        ports: [3000:3000]
        environment:
            - PORT=3000
            - HOST=localhost:3000
            - JOURNAL_DB_NAME=Journal
            - JOURNAL_DB_HOST=auth_db
            - JOURNAL_DB_USER=root
            - JOURNAL_DB_PASS=diaryJournal
            - SALT_ROUNDS=15
            - JOURNAL_EMAIL_SECRET=journalSecret
            - JOURNAL_ACCESS_SECRET=journalAccess
            - JOURNAL_REFRESH_SECRET=journalRefresh
            - NODE_ENV=development
        volumes:
            - ./src:/usr/src/app/src
        networks:
            - journal-network
        depends_on: [auth_db]
        restart: always
networks:
    journal-network:
        driver: bridge
